# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  desc "Bump the version code"
  lane :bumpVersionCode do
    android_set_version_code(
      gradle_file: "app/App_Resources/Android/app.gradle" # optional
    )
  end

  desc "Deploy a new version to the Google Play store"
  lane :GPlayInternal do
    upload_to_play_store(track: "internal")
  end
end